[env]
PROJECT_NAME = "{{ config_root | basename }}"

[settings]
python.uv_venv_auto = true

[tools]
python = "{{ get_env(name='PYTHON_VERSION', default='3.13') }}"
ruff = "latest"

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "uv sync"

[tasks.serve]
description = "Serve the application"
run = "mkdocs serve"

[tasks.lint]
description = "Lint the code"
run = "ruff check ."

[tasks.info]
description = "Print project information"
run = '''
echo "Project: $PROJECT_NAME"
echo "Virtual Environment: $VIRTUAL_ENV"
'''